eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8080/eureka/
  instance:
    prefer-ip-address: true

turbine:
  appConfig: "customer,preference"
  clusterNameExpression: new String("default")

hystrix:
  dashboard:
    proxyStreamAllowList: '*'

server:
  port: 8080
